apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: redis-enterprise
  namespace: ecommerce
spec:
  nodes: 3
  persistentSpec:
    enabled: true
    storageClassName: "premium-rwo"