apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
namePrefix: staging-
commonLabels:
  environment: staging

images:
- name: ecommerce/product-catalog
  newTag: latest
- name: encryption-service
  newTag: latest
