apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
namePrefix: prod-
commonLabels:
  environment: production

images:
- name: ecommerce/product-catalog
  newTag: v1.0.0
- name: encryption-service
  newTag: v1.0.0

patches:
- target:
    kind: Deployment
    name: product-catalog
  patch: 
    - op: replace
      path: /spec/replicas
      value: 5