apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
namePrefix: us-
commonLabels:
  region: us
  cluster: primary

patches:
- target:
    kind: Deployment
    name: product-catalog
  patch: 
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: us-redis.ecommerce.svc.cluster.local