apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog
  namespace: ecommerce
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-catalog
  template:
    metadata:
      labels:
        app: product-catalog
    spec:
      containers:
      - name: product-catalog
        image: ecommerce/product-catalog:latest
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          value: redis.ecommerce.svc.cluster.local
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
      - name: encryption-sidecar
        image: encryption-service:latest
        ports:
        - containerPort: 9090